resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: silo-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - Orleans__Clustering__ProviderType=Redis
    - Orleans__Clustering__ServiceKey=orleans-redis
    - Orleans__ClusterId=YI5gIY!wWXQTf47fEwHCMBdRZ
    - Orleans__ServiceId=AJqLjfRcRscwk7fOEe9wauq1w
    - Orleans__EnableDistributedTracing=true
    - Orleans__Endpoints__SiloPort=8000
    - Orleans__Endpoints__GatewayPort=8001
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=silo
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: silo-secrets
  envs:
  - .silo.secrets
