---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-orleans-api
  labels:
    app: non-orleans-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: non-orleans-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: non-orleans-api
    spec:
      containers:
      - name: non-orleans-api
        image: non-orleans-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: non-orleans-api-env
      terminationGracePeriodSeconds: 180