---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-client-api
  labels:
    app: orleans-client-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: orleans-client-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orleans-client-api
    spec:
      containers:
      - name: orleans-client-api
        image: orleans-client-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: orleans-client-api-env
        - secretRef:
            name: orleans-client-api-secrets
      terminationGracePeriodSeconds: 180