resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: orleans-client-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - Orleans__Clustering__ProviderType=Redis
    - Orleans__Clustering__ServiceKey=orleans-redis
    - Orleans__ClusterId=c!vn!VqurxS1FBVnW0wooJGka
    - Orleans__ServiceId=aHOF4n!xIe90wnG4ioEBPSwIA
    - Orleans__EnableDistributedTracing=true
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=orleans-client-api
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: orleans-client-api-secrets
  envs:
  - .orleans-client-api.secrets
